// src/config/tests.config.js
//
// Catálogo único de todos los tests físicos de RECKON. FitnessTestsForm.jsx
// y el generador de PDF se alimentan de esta misma fuente, así que agregar,
// editar o sacar un test se hace en UN solo lugar.
//
// `image` es una ruta relativa a /public/tests/ — por ahora son placeholders;
// reemplazalas por fotos/clips cortos (inicio/fin) tuyos cuando los filmes.
// Mientras no exista el archivo, TestCard muestra un ícono en su lugar, así
// que no rompe nada tener la ruta "vacía" todavía.
//
// mode:
//  - 'self'          cualquiera lo hace sin ayuda ni equipamiento especial
//  - 'helper'        mejor con alguien que tome el tiempo o mida
//  - 'professional'  requiere elemento específico o lectura técnica (caliper,
//                     pulsómetro, goniómetro) — se oculta en modo "Solo"
//
// highIntensity: true → se bloquea automáticamente si el PAR-Q dio positivo
// (ver TestCard). No es exhaustivo a nivel clínico, es un filtro de sentido
// común para evitar que alguien con PAR-Q positivo se tire a hacer un Cooper.

export const TESTS = [
    // ───────────────── MOVILIDAD ARTICULAR ─────────────────
    {
      id: 'apley_scratch',
      section: 'movilidad',
      title: 'Apley Scratch (hombro)',
      mode: 'helper',
      purpose: 'Mide cuánto podés rotar el hombro en flexión y extensión combinadas.',
      equipment: 'Ninguno (ideal: alguien que observe desde atrás)',
      image: 'tests/apley-scratch.jpg',
      steps: [
        'Pasá un brazo por arriba del hombro y bajá la mano por la espalda.',
        'Pasá el otro brazo por abajo, desde la cintura hacia arriba.',
        'Intentá que los dedos de ambas manos se toquen o se acerquen.',
        'Repetí cambiando qué brazo va arriba y cuál abajo.',
      ],
      commonMistakes: ['Forzar el movimiento con dolor', 'Comparar solo un lado y no el otro'],
      highIntensity: false,
      inputs: [{ key: 'apley_scratch', label: 'Resultado', type: 'text', placeholder: 'Ej: alcanza L5, falta 5cm' }],
    },
    {
      id: 'thomas_test',
      section: 'movilidad',
      title: 'Test de Thomas (cadera)',
      mode: 'helper',
      purpose: 'Detecta acortamiento del flexor de cadera (psoas/recto femoral).',
      equipment: 'Camilla, cama o mesa donde colgar una pierna',
      image: 'tests/thomas-test.jpg',
      steps: [
        'Sentate en el borde de una cama y acostate llevando ambas rodillas al pecho.',
        'Soltá una pierna dejándola colgar fuera del borde, sosteniendo la otra contra el pecho.',
        'Observá si el muslo que cuelga queda paralelo al piso o se eleva.',
        'Repetí del otro lado.',
      ],
      commonMistakes: ['Hacerlo sin que la zona lumbar esté apoyada', 'No comparar ambos lados'],
      highIntensity: false,
      inputs: [{ key: 'thomas_test', label: 'Resultado', type: 'text', placeholder: 'Ej: pierna izq elevada 15cm' }],
    },
    {
      id: 'knee_to_wall',
      section: 'movilidad',
      title: 'Knee-to-wall (tobillo)',
      mode: 'self',
      purpose: 'Mide la dorsiflexión de tobillo — clave para sentadillas profundas.',
      equipment: 'Una pared y una cinta métrica',
      image: 'tests/knee-to-wall.jpg',
      steps: [
        'Parate de frente a una pared, con un pie apuntando hacia ella.',
        'Doblá la rodilla tratando de tocar la pared sin levantar el talón.',
        'Alejá el pie de a poco hasta la máxima distancia donde todavía podés tocar la pared sin despegar el talón.',
        'Medí esa distancia entre el dedo gordo y la pared.',
      ],
      commonMistakes: ['Levantar el talón del piso', 'Medir con la rodilla rotada hacia afuera'],
      highIntensity: false,
      inputs: [{ key: 'knee_to_wall_cm', label: 'Distancia', type: 'number', unit: 'cm', min: 0, max: 25 }],
    },
    {
      id: 'thoracic_rotation',
      section: 'movilidad',
      title: 'Rotación torácica',
      mode: 'helper',
      purpose: 'Evalúa cuánto rota tu columna media/alta — importante en levantamientos.',
      equipment: 'Un bastón o palo de escoba (opcional)',
      image: 'tests/thoracic-rotation.jpg',
      steps: [
        'Arrodillate con las caderas quietas (podés apoyarte contra una pared con la cadera).',
        'Cruzá los brazos sobre el pecho o sostené un bastón.',
        'Rotá el torso hacia un lado lo más que puedas sin mover la cadera.',
        'Un ayudante estima el ángulo alcanzado, o filmalo desde arriba y comparalo con una regla visual.',
      ],
      commonMistakes: ['Dejar que la cadera rote junto con el torso'],
      highIntensity: false,
      inputs: [{ key: 'thoracic_rotation_deg', label: 'Ángulo', type: 'number', unit: '°', min: 0, max: 90 }],
    },
    {
      id: 'lumbar_extension',
      section: 'movilidad',
      title: 'Extensión lumbar (prone press-up)',
      mode: 'self',
      purpose: 'Chequea movilidad y dolor en extensión de zona lumbar.',
      equipment: 'Ninguno',
      image: 'tests/lumbar-extension.jpg',
      steps: [
        'Acostate boca abajo, manos a la altura de los hombros.',
        'Empujá con los brazos levantando el torso, dejando la cadera en el piso.',
        'Subí hasta donde puedas sin dolor agudo (una molestia leve de estiramiento es normal).',
        'Anotá si hubo dolor y en qué punto del recorrido apareció.',
      ],
      commonMistakes: ['Forzar el rango si aparece dolor agudo (no muscular)'],
      highIntensity: false,
      contraindication: 'Si tenés dolor lumbar en reposo, hacé este test con cuidado y detenete ante cualquier dolor agudo.',
      inputs: [{ key: 'lumbar_extension_notes', label: 'Observaciones', type: 'text', placeholder: 'Dolor vs movilidad observada...' }],
    },
  
    // ───────────────── ESTABILIDAD Y CONTROL MOTOR ─────────────────
    {
      id: 'plank',
      section: 'estabilidad',
      title: 'Plancha (plank)',
      mode: 'self',
      purpose: 'Mide resistencia del core en una postura isométrica.',
      equipment: 'Ninguno',
      image: 'tests/plank.jpeg',
      hasTimer: true,
      steps: [
        'Apoyate sobre antebrazos y puntas de pie, cuerpo en línea recta de cabeza a talones.',
        'No dejes caer la cadera ni la levantes de más.',
        'Mantené la postura el mayor tiempo posible con buena forma.',
        'Parate apenas la forma se rompa (cadera cae, espalda se curva).',
      ],
      commonMistakes: ['Dejar caer la cadera', 'Levantar la cola para "aguantar más"'],
      highIntensity: false,
      inputs: [{ key: 'plank_sec', label: 'Tiempo', type: 'number', unit: 'seg', min: 0, max: 600 }],
    },
    {
      id: 'side_plank',
      section: 'estabilidad',
      title: 'Plancha lateral (ambos lados)',
      mode: 'self',
      purpose: 'Detecta asimetrías de fuerza entre el lado izquierdo y derecho del core.',
      equipment: 'Ninguno',
      image: 'tests/side-plank.jpg',
      hasTimer: true,
      steps: [
        'Acostate de lado, apoyado en un antebrazo, cuerpo en línea recta.',
        'Levantá la cadera del piso y sostené.',
        'Cronometrá cada lado por separado — vas a necesitar dos intentos.',
      ],
      commonMistakes: ['Dejar caer la cadera hacia el piso', 'Comparar un lado bien hecho con otro mal hecho'],
      highIntensity: false,
      inputs: [
        { key: 'side_plank_left_sec', label: 'Lado izquierdo', type: 'number', unit: 'seg', min: 0, max: 300 },
        { key: 'side_plank_right_sec', label: 'Lado derecho', type: 'number', unit: 'seg', min: 0, max: 300 },
      ],
    },
    {
      id: 'bird_dog',
      section: 'estabilidad',
      title: 'Bird dog',
      mode: 'self',
      purpose: 'Evalúa control motor lumbopélvico y coordinación brazo-pierna opuesta.',
      equipment: 'Ninguno',
      image: 'tests/bird-dog.jpeg',
      steps: [
        'Apoyate en cuatro patas, manos bajo hombros, rodillas bajo cadera.',
        'Extendé un brazo y la pierna opuesta al mismo tiempo, sin que la espalda se mueva.',
        'Volvé a la posición inicial con control (sin caer de golpe).',
        'Contá solo las repeticiones que hiciste sin perder el equilibrio ni mover la cadera.',
      ],
      commonMistakes: ['Rotar la cadera al extender la pierna', 'Ir muy rápido perdiendo control'],
      highIntensity: false,
      inputs: [{ key: 'bird_dog_reps', label: 'Repeticiones controladas', type: 'number', min: 0, max: 50 }],
    },
    {
      id: 'dead_bug',
      section: 'estabilidad',
      title: 'Dead bug',
      mode: 'self',
      purpose: 'Mide estabilidad lumbar al mover brazos y piernas de forma independiente.',
      equipment: 'Ninguno',
      image: 'tests/dead-bug.jpg',
      steps: [
        'Acostate boca arriba, brazos al techo, rodillas y caderas en 90°.',
        'Bajá un brazo y la pierna opuesta hacia el piso, sin que la zona lumbar se despegue.',
        'Volvé a la posición inicial y repetí del otro lado.',
        'Contá solo las repeticiones donde la espalda baja se mantuvo pegada al piso.',
      ],
      commonMistakes: ['Despegar la zona lumbar del piso'],
      highIntensity: false,
      inputs: [{ key: 'dead_bug_reps', label: 'Repeticiones', type: 'number', min: 0, max: 50 }],
    },
    {
      id: 'single_leg_glute_bridge',
      section: 'estabilidad',
      title: 'Puente de glúteos a una pierna',
      mode: 'self',
      purpose: 'Fuerza y estabilidad de cadera en apoyo unipodal.',
      equipment: 'Ninguno',
      image: 'tests/glute-bridge.jpg',
      steps: [
        'Acostate boca arriba, una rodilla flexionada con el pie en el piso.',
        'Estirá la otra pierna al aire.',
        'Levantá la cadera empujando con el talón apoyado, sin que la cadera se incline hacia los costados.',
        'Contá repeticiones controladas de cada lado.',
      ],
      commonMistakes: ['Dejar que la cadera caiga hacia un lado'],
      highIntensity: false,
      inputs: [{ key: 'single_leg_glute_bridge_reps', label: 'Repeticiones', type: 'number', min: 0, max: 50 }],
    },
    {
      id: 'y_balance',
      section: 'estabilidad',
      title: 'Y-balance (simplificado)',
      mode: 'professional',
      purpose: 'Estima riesgo de lesión de miembro inferior por asimetrías de alcance.',
      equipment: 'Cinta en el piso marcando 3 direcciones, o cinta métrica',
      image: 'tests/y-balance.jpg',
      steps: [
        'Parado en una pierna, alcanzá con la otra lo más lejos posible en 3 direcciones (adelante, atrás-adentro, atrás-afuera) sin perder el equilibrio.',
        'Medí cada alcance y repetí con la otra pierna de apoyo.',
        'Compará asimetrías entre ambos lados.',
      ],
      commonMistakes: ['Perder el equilibrio y apoyar la pierna que alcanza'],
      highIntensity: false,
      inputs: [{ key: 'y_balance_notes', label: 'Alcances / asimetrías', type: 'text', placeholder: 'Anotá en cm o describí asimetrías' }],
    },
  
    // ───────────────── FUERZA MÁXIMA ESTIMADA ─────────────────
    {
      id: 'pushup',
      section: 'fuerza',
      title: 'Push-ups (flexiones de brazos)',
      mode: 'self',
      purpose: 'Estima fuerza-resistencia de tren superior.',
      equipment: 'Ninguno',
      image: 'tests/pushup.jpeg',
      steps: [
        'Apoyate en manos y puntas de pie (o rodillas, si no podés en puntas de pie), cuerpo recto.',
        'Bajá hasta casi tocar el piso con el pecho.',
        'Subí extendiendo los brazos completamente.',
        'Contá solo las repeticiones completas, hasta que no puedas mantener la técnica.',
      ],
      commonMistakes: ['No bajar lo suficiente', 'Arquear o hundir la cadera'],
      highIntensity: false,
      inputs: [{ key: 'pushup_reps', label: 'Repeticiones máximas', type: 'number', min: 0, max: 100 }],
    },
    {
      id: 'max_squat',
      section: 'fuerza',
      title: 'Sentadilla con peso corporal (máx. reps)',
      mode: 'self',
      purpose: 'Estima fuerza-resistencia de tren inferior.',
      equipment: 'Ninguno',
      image: 'tests/bodyweight-squat.jpg',
      steps: [
        'Parado, pies al ancho de hombros, bajá flexionando rodillas y cadera como si te fueras a sentar.',
        'Bajá hasta que los muslos queden paralelos al piso (o lo más cerca posible, sin dolor).',
        'Subí hasta extender completamente las piernas.',
        'Contá repeticiones hasta que la técnica se rompa.',
      ],
      commonMistakes: ['No bajar lo suficiente', 'Rodillas colapsando hacia adentro'],
      highIntensity: false,
      inputs: [{ key: 'max_squat_reps', label: 'Repeticiones máximas', type: 'number', min: 0, max: 150 }],
    },
    {
      id: 'max_pullup',
      section: 'fuerza',
      title: 'Dominadas / remo invertido',
      mode: 'helper',
      purpose: 'Estima fuerza de tracción de tren superior.',
      equipment: 'Barra fija o mesa resistente para remo invertido',
      image: 'tests/pullup.jpg',
      steps: [
        'Si tenés barra: colgate y tirá hasta que el mentón pase la barra, sin balancearte.',
        'Si no tenés barra: hacé remo invertido bajo una mesa firme, tirando el pecho hacia ella.',
        'Contá solo repeticiones completas.',
      ],
      commonMistakes: ['Usar impulso de las piernas o balanceo del cuerpo'],
      highIntensity: false,
      inputs: [{ key: 'max_pullup_reps', label: 'Repeticiones máximas', type: 'number', min: 0, max: 50 }],
    },
    {
      id: 'wall_sit',
      section: 'fuerza',
      title: 'Sentadilla contra la pared (wall sit)',
      mode: 'self',
      purpose: 'Resistencia isométrica de cuádriceps.',
      equipment: 'Una pared',
      image: 'tests/wall-sit.jpg',
      hasTimer: true,
      steps: [
        'Apoyá la espalda contra la pared y bajá hasta que las rodillas queden en 90°.',
        'Sostené la posición el mayor tiempo posible.',
        'Parate cuando ya no puedas mantener el ángulo.',
      ],
      commonMistakes: ['Dejar que las rodillas pasen la punta de los pies'],
      highIntensity: false,
      inputs: [{ key: 'wall_sit_sec', label: 'Tiempo', type: 'number', unit: 'seg', min: 0, max: 600 }],
    },
    {
      id: 'plank_to_pushup',
      section: 'fuerza',
      title: 'Plancha + push-up (combinado)',
      mode: 'self',
      purpose: 'Combina fuerza de core y tren superior con un patrón de transición.',
      equipment: 'Ninguno',
      image: 'tests/plank-to-pushup.jpg',
      steps: [
        'Empezá en plancha sobre antebrazos.',
        'Subí a plancha alta apoyando una mano y después la otra (como un push-up invertido).',
        'Volvé a antebrazos, alternando qué brazo sube primero.',
        'Contá repeticiones completas sin que la cadera se mueva de lado a lado.',
      ],
      commonMistakes: ['Mover la cadera de lado a lado al cambiar de apoyo'],
      highIntensity: false,
      inputs: [{ key: 'plank_to_pushup_reps', label: 'Repeticiones', type: 'number', min: 0, max: 50 }],
    },
  
    // ───────────────── POTENCIA Y VELOCIDAD ─────────────────
    {
      id: 'vertical_jump',
      section: 'potencia',
      title: 'Salto vertical',
      mode: 'helper',
      purpose: 'Potencia explosiva de tren inferior.',
      equipment: 'Pared y algo para marcar la altura (tiza, cinta)',
      image: 'tests/vertical-jump.jpg',
      highIntensity: true,
      steps: [
        'Parado de costado a la pared, marcá tu altura con el brazo extendido hacia arriba.',
        'Saltá lo más alto posible y marcá el punto más alto que toques.',
        'Medí la diferencia entre ambas marcas.',
      ],
      commonMistakes: ['Dar un paso antes de saltar (debe ser salto parado)'],
      inputs: [{ key: 'vertical_jump_cm', label: 'Altura', type: 'number', unit: 'cm', min: 0, max: 100 }],
    },
    {
      id: 'broad_jump',
      section: 'potencia',
      title: 'Salto horizontal',
      mode: 'helper',
      purpose: 'Potencia de tren inferior en el plano horizontal.',
      equipment: 'Cinta métrica o espacio marcado en el piso',
      image: 'tests/broad-jump.jpg',
      highIntensity: true,
      steps: [
        'Parado con los pies juntos detrás de una línea.',
        'Saltá lo más lejos posible, cayendo con ambos pies a la vez.',
        'Medí desde la línea de partida hasta el talón más cercano a la línea.',
      ],
      commonMistakes: ['Caer con un pie adelantado y medir desde ahí'],
      inputs: [{ key: 'broad_jump_cm', label: 'Distancia', type: 'number', unit: 'cm', min: 0, max: 400 }],
    },
    {
      id: 'medball_throw',
      section: 'potencia',
      title: 'Lanzamiento de medicine ball',
      mode: 'professional',
      purpose: 'Potencia de tren superior.',
      equipment: 'Medicine ball',
      image: 'tests/medball-throw.jpg',
      highIntensity: true,
      steps: [
        'Sentado contra una pared (para que no ayude el tronco), sostené la pelota contra el pecho.',
        'Lanzá hacia adelante con la máxima potencia posible.',
        'Medí la distancia desde el punto de lanzamiento hasta donde cae.',
      ],
      commonMistakes: ['Hacerlo parado, usando el impulso de todo el cuerpo'],
      inputs: [{ key: 'medball_throw_m', label: 'Distancia', type: 'number', unit: 'm', min: 0, max: 15, step: 0.1 }],
    },
    {
      id: 'sprint_10m',
      section: 'potencia',
      title: 'Sprint 10m',
      mode: 'helper',
      purpose: 'Velocidad de aceleración.',
      equipment: 'Cronómetro (o app de celular) y espacio de 10m',
      image: 'tests/sprint-10m.jpeg',
      highIntensity: true,
      steps: [
        'Marcá 10 metros en un espacio plano y seguro.',
        'Arrancá desde parado y corré lo más rápido posible los 10m.',
        'Un ayudante cronometra desde que te movés hasta que cruzás la marca.',
      ],
      commonMistakes: ['Arrancar con impulso previo en vez de parado'],
      inputs: [{ key: 'sprint_10m_sec', label: 'Tiempo', type: 'number', unit: 'seg', min: 0, max: 10, step: 0.01 }],
    },
    {
      id: 'agility_5_10_5',
      section: 'potencia',
      title: 'Test de agilidad 5-10-5',
      mode: 'helper',
      purpose: 'Capacidad de cambiar de dirección rápidamente.',
      equipment: 'Cronómetro y 3 conos o marcas en el piso',
      image: 'tests/agility-5-10-5.jpg',
      highIntensity: true,
      steps: [
        'Marcá tres líneas separadas por 5 metros cada una.',
        'Desde el centro, corré 5m a un lado, tocá la línea, volvé 10m al otro extremo, tocá, y volvé 5m al centro.',
        'Cronometrá el tiempo total del recorrido.',
      ],
      commonMistakes: ['No tocar la línea antes de cambiar de dirección'],
      inputs: [{ key: 'agility_5_10_5_sec', label: 'Tiempo', type: 'number', unit: 'seg', min: 0, max: 30, step: 0.01 }],
    },
  
    // ───────────────── CAPACIDAD AERÓBICA ─────────────────
    {
      id: 'cooper',
      section: 'aerobica',
      title: 'Test de Cooper (12 minutos)',
      mode: 'helper',
      purpose: 'Estima tu capacidad aeróbica (VO2max) según la distancia recorrida.',
      equipment: 'Cronómetro y una pista o espacio para correr/caminar 12 minutos',
      image: 'tests/cooper.webp',
      highIntensity: true,
      steps: [
        'Corré o caminá a paso rápido durante 12 minutos continuos.',
        'Mantené el ritmo más constante posible, sin arrancar muy fuerte y frenar después.',
        'Medí la distancia total recorrida (con una app de running o una pista marcada).',
      ],
      commonMistakes: ['Arrancar demasiado rápido y no poder sostener el ritmo'],
      contraindication: 'Es un test de esfuerzo exigente. No lo hagas si el PAR-Q dio positivo sin autorización médica.',
      inputs: [{ key: 'cooper_distance_m', label: 'Distancia recorrida', type: 'number', unit: 'm', min: 0, max: 5000 }],
    },
    {
      id: 'two_step',
      section: 'aerobica',
      title: 'Test de recuperación (2-step)',
      mode: 'helper',
      purpose: 'Qué tan rápido baja tu frecuencia cardíaca después de un esfuerzo.',
      equipment: 'Pulsómetro o cómo tomarte el pulso manualmente',
      image: 'tests/two-step.webp',
      highIntensity: true,
      steps: [
        'Hacé un esfuerzo moderado-alto durante 3 minutos (subir escalones, sentadillas rápidas).',
        'Al terminar, medí tu frecuencia cardíaca inmediatamente y de nuevo al minuto.',
        'Anotá la frecuencia cardíaca al minuto de recuperación.',
      ],
      commonMistakes: ['Medir el pulso mucho después del minuto exacto'],
      inputs: [{ key: 'two_step_hr_recovery', label: 'FC al minuto', type: 'number', unit: 'lpm', min: 40, max: 220 }],
    },
    {
      id: 'rpe_3min_walk',
      section: 'aerobica',
      title: 'RPE tras 3 minutos de marcha rápida',
      mode: 'self',
      purpose: 'Percepción subjetiva de esfuerzo — útil si no tenés pulsómetro.',
      equipment: 'Ninguno',
      image: 'tests/rpe-walk.webp',
      steps: [
        'Caminá a paso rápido (el más rápido que puedas sostener) durante 3 minutos.',
        'Al terminar, calificá tu esfuerzo percibido del 1 (nada) al 10 (máximo posible).',
      ],
      commonMistakes: [],
      highIntensity: false,
      inputs: [{ key: 'rpe_3min_walk', label: 'Esfuerzo percibido', type: 'number', unit: '/10', min: 1, max: 10 }],
    },
    {
      id: 'talk_test',
      section: 'aerobica',
      title: 'Talk test',
      mode: 'self',
      purpose: 'Estima tu umbral ventilatorio según si podés hablar mientras hacés esfuerzo.',
      equipment: 'Ninguno',
      image: 'tests/talk-test.webp',
      steps: [
        'Mientras hacés un esfuerzo moderado (caminar rápido, trote suave), intentá hablar en voz alta.',
        'Evaluá si podés mantener una conversación fluida, hablar con dificultad, o no podés hablar.',
      ],
      commonMistakes: [],
      highIntensity: false,
      inputs: [{
        key: 'talk_test_result', label: 'Resultado', type: 'select',
        options: ['Puedo hablar fluido', 'Puedo hablar con dificultad', 'No puedo hablar'],
      }],
    },
  
    // ───────────────── TESTS STANDALONE (funcionales) ─────────────────
    {
      id: 'chair_test',
      section: 'funcional',
      title: 'Test de la silla (sentarse-levantarse)',
      mode: 'self',
      purpose: 'Fuerza funcional de tren inferior — muy usado con adultos mayores y principiantes.',
      equipment: 'Una silla sin apoyabrazos',
      image: 'tests/chair-test.jpg',
      hasTimer: true,
      timerTargetSec: 30,
      steps: [
        'Sentate en el centro de la silla, brazos cruzados sobre el pecho.',
        'Durante 30 segundos, parate completamente y volvé a sentarte, tantas veces como puedas.',
        'No uses los brazos para impulsarte.',
      ],
      commonMistakes: ['Usar los brazos para ayudarse a parar', 'No extender completamente las piernas al parar'],
      highIntensity: false,
      inputs: [
        { key: 'chair_test_reps', label: 'Repeticiones en 30 seg', type: 'number', min: 0, max: 60 },
      ],
    },
    {
      id: 'deep_squat',
      section: 'funcional',
      title: 'Sentadilla profunda (movilidad global)',
      mode: 'self',
      purpose: 'Evalúa movilidad combinada de tobillo, cadera, columna y hombros.',
      equipment: 'Ninguno (opcional: un palo para sostener arriba de la cabeza)',
      image: 'tests/deep-squat.jpg',
      steps: [
        'Parado, pies al ancho de hombros, brazos extendidos arriba de la cabeza.',
        'Bajá en sentadilla lo más profundo que puedas, manteniendo talones en el piso y brazos arriba.',
        'Observá hasta dónde llegás sin perder la postura.',
      ],
      commonMistakes: ['Levantar los talones', 'Dejar caer los brazos hacia adelante'],
      highIntensity: false,
      inputs: [
        { key: 'deep_squat_depth', label: 'Profundidad alcanzada', type: 'select', options: ['Incompleta', 'Paralela', 'Completa'] },
        { key: 'deep_squat_compensation', label: 'Compensaciones observadas', type: 'text', placeholder: 'Valgo de rodilla, inclinación de tronco...' },
      ],
    },
    {
      id: 'balance',
      section: 'funcional',
      title: 'Equilibrio unipodal',
      mode: 'self',
      purpose: 'Control de estabilidad en apoyo de una sola pierna.',
      equipment: 'Ninguno',
      image: 'tests/balance.jpg',
      hasTimer: true,
      steps: [
        'Parate en una pierna, ojos abiertos, mirando al frente.',
        'Cronometrá cuánto tiempo aguantás sin apoyar la otra pierna ni agarrarte de algo.',
        'Repetí con la otra pierna.',
      ],
      commonMistakes: ['Mirar hacia abajo (hace más fácil el test)'],
      highIntensity: false,
      inputs: [
        { key: 'balance_dominant_sec', label: 'Pierna dominante', type: 'number', unit: 'seg', min: 0, max: 180 },
        { key: 'balance_nondominant_sec', label: 'Pierna no dominante', type: 'number', unit: 'seg', min: 0, max: 180 },
      ],
    },
    {
      id: 'srt',
      section: 'funcional',
      title: 'Sentarse-levantarse del suelo (SRT)',
      mode: 'self',
      purpose: 'Combina fuerza, movilidad y equilibrio — predictor general de condición física.',
      equipment: 'Ninguno',
      image: 'tests/srt.jpg',
      steps: [
        'Parado descalzo, sentate en el piso y después volvé a pararte, usando la menor cantidad de apoyos posible (manos, rodillas, antebrazos).',
        'Empezás con 10 puntos y restás 1 por cada apoyo que uses (0.5 si perdés el equilibrio).',
        'Anotá el puntaje final.',
      ],
      commonMistakes: ['No avisar antes que es normal tambalearse un poco'],
      highIntensity: false,
      inputs: [{ key: 'srt_score', label: 'Puntaje (0-10)', type: 'number', min: 0, max: 10, step: 0.5 }],
    },
    {
      id: 'step_test',
      section: 'funcional',
      title: 'Test del escalón (3 minutos)',
      mode: 'helper',
      purpose: 'Estima capacidad aeróbica sin necesidad de correr.',
      equipment: 'Un escalón de ~30cm y cronómetro',
      image: 'tests/step-test.jpg',
      highIntensity: true,
      steps: [
        'Subí y bajá un escalón de 30cm a ritmo constante durante 3 minutos.',
        'Al terminar, sentate y medí tu frecuencia cardíaca 60 segundos después.',
      ],
      commonMistakes: ['Cambiar el ritmo durante el test'],
      inputs: [
        { key: 'step_test_heart_rate', label: 'FC post-ejercicio', type: 'number', unit: 'lpm', min: 40, max: 220 },
      ],
    },
  ];
  
  export const SECTIONS = [
    { id: 'movilidad', title: 'Movilidad Articular', description: 'Rangos de movimiento clave para prevenir lesiones.' },
    { id: 'estabilidad', title: 'Estabilidad y Control Motor', description: 'Core, asimetrías y control lumbopélvico.' },
    { id: 'fuerza', title: 'Fuerza Máxima Estimada', description: 'Tests sin equipo para estimar fuerza relativa.' },
    { id: 'potencia', title: 'Potencia y Velocidad', description: 'Expresiones de potencia neuromuscular.' },
    { id: 'aerobica', title: 'Capacidad Aeróbica', description: 'Tests de campo para resistencia cardiovascular.' },
    { id: 'funcional', title: 'Tests Funcionales', description: 'Fuerza, movilidad y equilibrio combinados.' },
  ];
  
  export const SKIP_REASONS = [
    'Dolor',
    'Mareo o falta de aire',
    'No tengo el elemento necesario',
    'Prefiero no hacerlo ahora',
  ];
  
  export const MODE_LABELS = {
    self: { label: 'Autoevaluable', color: 'bg-green-50 text-green-700 border-green-200' },
    helper: { label: 'Con ayuda', color: 'bg-blue-50 text-blue-700 border-blue-200' },
    professional: { label: 'Con profesional', color: 'bg-purple-50 text-purple-700 border-purple-200' },
  };